version: '3'
services:
  apache:
    build:
      context: .docker/images/apache
      dockerfile: Dockerfile
    container_name: moodle
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - './www:/app:consistent'
      - '~/moodledata/:/moodledata:consistent'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
        - './data/mysql:/var/lib/mysql'
